# @package network
defaults:
  - _base
  - _self_

network_type: "chiunet"
emb_dim: 256
num_layers: 6  # Not directly used, but kept for compatibility
dropout: 0.0
timestep_emb_dim: 128

# ChiUNet specific configs, this setting gives around 20M parameters
model_dim: 128
kernel_size: 5
cond_predict_scale: true
obs_as_global_cond: true
dim_mult: [1, 2, 2]  # Dimension multipliers for U-Net layers
timestep_emb_type: "positional"
skip_scale: 1.0
cond_dropout_rate: 0.0
